// Generates supabase-setup.sql: the full schema plus seeded demo data as one
// SQL file that can be pasted into the Supabase SQL Editor — the no-terminal
// setup path. Run against a freshly seeded local database:
//   npm run db:reset && npx tsx scripts/export-supabase-setup.ts
//
// The file also records Drizzle's migration bookkeeping so a later
// `npm run db:migrate` against the same database only applies new migrations.

import fs from "node:fs";
import { sql } from "drizzle-orm";
import { getTableColumns } from "drizzle-orm";
import type { PgTable } from "drizzle-orm/pg-core";
import { getTableConfig } from "drizzle-orm/pg-core";
import { db, closeDb } from "../src/db";
import * as t from "../src/db/schema";

// Insert order respects foreign keys.
const TABLES: PgTable[] = [
  t.users,
  t.customers,
  t.customerContacts,
  t.externalParties,
  t.applications,
  t.loans,
  t.assets,
  t.applicationAssets,
  t.applicationChecklistItems,
  t.insurancePolicies,
  t.insurancePolicyAssets,
  t.documents,
  t.loanSchedules,
  t.transactions,
  t.directDebitAuthorities,
  t.ppsrRegistrations,
  t.ppsrEvents,
  t.searches,
  t.auditLog,
];

function literal(value: unknown): string {
  if (value == null) return "NULL";
  if (typeof value === "boolean") return value ? "TRUE" : "FALSE";
  if (typeof value === "number") return String(value);
  return `'${String(value).replace(/'/g, "''")}'`;
}

async function main() {
  const parts: string[] = [];
  parts.push(`-- YGG Loan Management System — one-shot Supabase setup
-- Paste this whole file into the Supabase SQL Editor and click Run.
-- It creates the full schema and loads the demo data (staff logins use
-- password "yellowgate" — change them in the app's Staff screen).
--
-- WARNING: this RESETS the database first — it drops everything in the
-- "public" schema, so any previous (or partial) run is cleaned up and the
-- script can be re-run safely. Do not run it against a database whose data
-- you want to keep.
-- Generated by scripts/export-supabase-setup.ts.

DROP SCHEMA IF EXISTS "drizzle" CASCADE;
DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA public;
GRANT ALL ON SCHEMA public TO postgres;
GRANT USAGE ON SCHEMA public TO public;
DO $$
BEGIN
  -- Restore Supabase's default grants where its roles exist (no-op elsewhere).
  IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'anon') THEN
    GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
    GRANT ALL ON SCHEMA public TO service_role;
  END IF;
END $$;
`);

  // 1. Schema — the committed Drizzle migration(s), in journal order.
  const journal = JSON.parse(fs.readFileSync("drizzle/meta/_journal.json", "utf8")) as {
    entries: Array<{ tag: string }>;
  };
  for (const entry of journal.entries) {
    parts.push(`-- === migration ${entry.tag} ===`);
    parts.push(fs.readFileSync(`drizzle/${entry.tag}.sql`, "utf8"));
  }

  // 2. Drizzle migration bookkeeping, copied from the local database so that
  //    future `npm run db:migrate` runs skip what this file already applied.
  type MigrationRow = { hash: string; created_at: string | number };
  // postgres-js returns the rows array directly; PGlite wraps them in {rows}.
  const bookkeeping = (await db.execute(
    sql`select hash, created_at from drizzle.__drizzle_migrations order by id`,
  )) as unknown as MigrationRow[] | { rows: MigrationRow[] };
  const migrationRows = Array.isArray(bookkeeping) ? bookkeeping : bookkeeping.rows;
  parts.push(`-- === drizzle migration bookkeeping ===
CREATE SCHEMA IF NOT EXISTS "drizzle";
CREATE TABLE IF NOT EXISTS "drizzle"."__drizzle_migrations" (
  id SERIAL PRIMARY KEY,
  hash text NOT NULL,
  created_at bigint
);`);
  for (const row of migrationRows) {
    parts.push(
      `INSERT INTO "drizzle"."__drizzle_migrations" ("hash", "created_at") VALUES (${literal(row.hash)}, ${row.created_at});`,
    );
  }

  // 3. Demo data.
  parts.push(`\n-- === demo data ===`);
  for (const table of TABLES) {
    const { name: tableName } = getTableConfig(table);
    const columns = getTableColumns(table);
    const keys = Object.keys(columns);
    const columnNames = keys.map((k) => `"${columns[k as keyof typeof columns].name}"`);
    const rows = (await db.select().from(table)) as Array<Record<string, unknown>>;
    if (rows.length === 0) continue;
    const values = rows
      .map((r) => `  (${keys.map((k) => literal(r[k])).join(", ")})`)
      .join(",\n");
    parts.push(
      `INSERT INTO "${tableName}" (${columnNames.join(", ")}) OVERRIDING SYSTEM VALUE VALUES\n${values};`,
    );
    if (keys.includes("id")) {
      parts.push(
        `SELECT setval(pg_get_serial_sequence('"${tableName}"', 'id'), (SELECT COALESCE(MAX("id"), 0) + 1 FROM "${tableName}"), false);`,
      );
    }
  }

  fs.writeFileSync("supabase-setup.sql", parts.join("\n") + "\n");
  console.log(`Wrote supabase-setup.sql (${TABLES.length} tables).`);
  await closeDb();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
