// Loads the ~1,600-deal test book into the local database:
//
//   npm run db:reset && npm run db:seed-scale
//
// The book itself is generated by src/lib/scale-book.ts — the same module
// behind the admin "Load test book" button on the Staff screen, which is how
// the book gets into the live (Supabase) database.

import { closeDb } from "../src/db";
import { generateScaleBook, insertScaleBook, isScaleBookLoaded } from "../src/lib/scale-book";

async function main() {
  if (await isScaleBookLoaded()) {
    console.log("Test book already loaded — run `npm run db:reset` first to regenerate.");
    await closeDb();
    return;
  }
  const book = generateScaleBook(Number(process.env.SCALE_DEALS ?? 1600));
  await insertScaleBook(book);
  const s = book.summary;
  console.log("Test book loaded:", s.counts);
  console.log(
    `Deals: ${s.deals} (${s.active} active, ${s.paidOut} paid out, ${s.writtenOff} written off, ${s.arrears} in arrears)`,
  );
  console.log(`Contracts ${s.firstContract}–${s.lastContract}, customers ${s.customers}`);
  console.log(`Open applications in the originations pipeline: ${s.openApplications}`);
  await closeDb();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
